import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import "../shared/styles/globals.scss";

import StoreProvider from "@/shared/lib/redux/store-provider";
import { makeStore } from "@/shared/lib/redux/store";
import { getCurrentUser } from "@/entities/user/model/api/getCurrentUser";
import { AuthModalProvider } from "@/components/AuthModal/provider/AuthModalProvider";
import AuthModalRoot from "@/components/AuthModal/AuthModalRoot";
// import AuthInit from '@/features/auth/model/AuthInit';
import { getServerUser } from "@/entities/user/model/api/getServerUser";
import { cookies } from "next/headers";
import ReferralCode from "@/features/referal-code/ReferralCode";

const proximaNova = localFont({
  src: [
    {
      path: "../../public/assets/fonts/ProximaNova/ProximaNovaBold/ProximaNovaBold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/ProximaNova/ProximaNovaRegular/ProximaNovaRegular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-proxima-nova",
  display: "swap",
});

const openSans = localFont({
  src: [
    {
      path: "../../public/assets/fonts/OpenSans/static/OpenSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/OpenSans/static/OpenSans-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/OpenSans/static/OpenSans-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/OpenSans/static/OpenSans-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-open-sans",
  display: "swap",
});

const roboto = localFont({
  src: [
    {
      path: "../../public/assets/fonts/Roboto/static/Roboto-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/Roboto/static/Roboto-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/Roboto/static/Roboto-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/Roboto/static/Roboto-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/Roboto/static/Roboto-Medium.ttf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-roboto",
  display: "swap",
});

const sanFranciscoProDisplay = localFont({
  src: [
    {
      path: "../../public/assets/fonts/SanFranciscoProDisplay/SF-Pro-Display-Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/SanFranciscoProDisplay/SF-Pro-Display-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-sf-pro-display",
  display: "swap",
});

const inter = localFont({
  src: [
    {
      path: "../../public/assets/fonts/Inter/static/Inter_18pt-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/Inter/static/Inter_18pt-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-inter",
  display: "swap",
});

const arial = localFont({
  src: [
    {
      path: "../../public/assets/fonts/arial/arial-regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-arial",
  display: "swap",
});

const tahoma = localFont({
  src: [
    {
      path: "../../public/assets/fonts/Tahoma/tahoma-regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-tahoma",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesStore = await cookies();

  let user = null;

  if (cookiesStore.get("refresh_token")) {
    user = await getServerUser();
  }

  const fontRootClassName = [
    proximaNova.variable,
    openSans.variable,
    roboto.variable,
    sanFranciscoProDisplay.variable,
    inter.variable,
    arial.variable,
    tahoma.variable,
  ].join(" ");

  return (
    <html lang="en" suppressHydrationWarning className={fontRootClassName}>
      <head>{/* <ColorSchemeScript /> */}</head>
      <body>
        <StoreProvider user={user}>
          <AuthModalProvider>
            {children}
            <ReferralCode />
            <AuthModalRoot />
          </AuthModalProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
